name: alsagr_app
description: A new Flutter project.
publish_to: "none"
version: 1.0.2+5

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  bot_toast: ^4.1.3
  cached_network_image: ^3.3.0
  carousel_slider: ^4.2.1
  cloud_firestore: ^4.9.1
  enefty_icons: ^1.0.5
  eva_icons_flutter: ^3.1.0
  expandable: ^5.0.1
  file_picker: ^4.1.4
  firebase_core: ^2.15.1
  firebase_storage: ^11.2.8
  flutter:
    sdk: flutter
  flutter_form_builder: ^9.1.1
  flutter_neumorphic: ^3.2.0
  flutter_pdfview: ^1.0.2
  font_awesome_flutter: ^10.3.0
  intl: ^0.18.1
  url_launcher: ^6.1.6
  
# icons_launcher:
#   image_path: "assets/app_icon.png"
#   platforms:
#     android:
#       enable: true
#     ios:
#       enable: true

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
    - shorebird.yaml
